using Npgsql;

namespace HemisAudit.Data
{
    // Creates the operational tables (engagements, assignments, validation runs, audit log,
    // sign-offs, messaging, favorites, rule scope) on the same Supabase Postgres database
    // that hosts Identity. There is no more separate "Users" mirror table — every user
    // reference here is a text FK straight to AspNetUsers("Id").
    public static class SystemDatabaseBootstrapper
    {
        public static async Task EnsureCreatedAsync(IConfiguration configuration)
        {
            var connectionString = PostgresConnectionStringHelper.WithResiliencyDefaults(
                configuration.GetConnectionString("Postgres")
                    ?? throw new InvalidOperationException("ConnectionStrings:Postgres is not configured."));

            // This runs once at startup, before any of the app's own retry/resiliency wrapping
            // is in play — a single transient Supabase hiccup here would otherwise crash the
            // whole app before it can start serving requests at all. The DDL below is entirely
            // idempotent (CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS), so retrying
            // the whole sequence on a transient failure is safe.
            const int maxAttempts = 3;
            for (var attempt = 1; ; attempt++)
            {
                try
                {
                    await using var connection = new NpgsqlConnection(connectionString);
                    await connection.OpenAsync();
                    await ExecuteSchemaAsync(connection);
                    return;
                }
                catch (Exception ex) when (attempt < maxAttempts && IsTransient(ex))
                {
                    await Task.Delay(500 * attempt);
                }
            }
        }

        private static bool IsTransient(Exception ex) =>
            ex is NpgsqlException
            || ex is System.Net.Sockets.SocketException
            || ex is System.IO.IOException
            || ex is TimeoutException;

        private static async Task ExecuteSchemaAsync(NpgsqlConnection connection)
        {
            var ddlStatements = new[]
            {
                @"CREATE TABLE IF NOT EXISTS ""Clients"" (
                    ""ClientID""        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""FirmID""          integer NOT NULL,
                    ""EngagementName""  varchar(255) NOT NULL,
                    ""MaconomyNumber""  varchar(100) NOT NULL UNIQUE,
                    ""Industry""        varchar(100) NULL,
                    ""DirectorName""    varchar(200) NOT NULL DEFAULT '',
                    ""DirectorEmail""   varchar(255) NOT NULL DEFAULT '',
                    ""DirectorEmpCode"" varchar(50)  NOT NULL DEFAULT '',
                    ""ManagerName""     varchar(200) NOT NULL DEFAULT '',
                    ""ManagerEmail""    varchar(255) NOT NULL DEFAULT '',
                    ""ManagerEmpCode""  varchar(50)  NOT NULL DEFAULT '',
                    ""Status""          varchar(50) NOT NULL DEFAULT 'Pending'
                                        CHECK (""Status"" IN ('Pending','Approved','Active','Archived','Rejected')),
                    ""CreatedBy""       text NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""ApprovedBy""      text NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""ApprovedAt""      timestamptz NULL,
                    ""ArchivedBy""      text NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""ArchivedAt""      timestamptz NULL,
                    ""CreatedAt""       timestamptz NOT NULL DEFAULT now()
                );",

                @"CREATE TABLE IF NOT EXISTS ""UserClientAssignments"" (
                    ""AssignmentID""   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserID""         text NOT NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""ClientID""       integer NOT NULL REFERENCES ""Clients""(""ClientID""),
                    ""EngagementRole"" varchar(50) NOT NULL DEFAULT 'DataAnalyst',
                    ""AssignedBy""     text NOT NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""AssignedAt""     timestamptz NOT NULL DEFAULT now(),
                    CONSTRAINT ""UQ_UserClientAssignments_User_Client"" UNIQUE (""UserID"", ""ClientID"")
                );",

                @"CREATE TABLE IF NOT EXISTS ""ValidationRuns"" (
                    ""RunID""          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ClientID""       integer NOT NULL REFERENCES ""Clients""(""ClientID""),
                    ""UserID""         text NOT NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""HemisServer""    varchar(255) NULL,
                    ""AuditDatabase""  varchar(255) NOT NULL,
                    ""StudTable""      varchar(255) NULL,
                    ""DeceasedTable""  varchar(255) NULL,
                    ""BridgeTable""    varchar(255) NULL,
                    ""CrseTable""      varchar(255) NULL,
                    ""StudColumn""     varchar(255) NULL,
                    ""DeceasedColumn"" varchar(255) NULL,
                    ""RuleNumber""     integer NULL,
                    ""RuleName""       varchar(255) NULL,
                    ""Status""         varchar(50) NULL,
                    ""RunTimestamp""   timestamptz NOT NULL DEFAULT now(),
                    ""TotalRecords""   integer NULL,
                    ""PassCount""      integer NULL,
                    ""FailCount""      integer NULL,
                    ""ExceptionRate""  numeric(10,4) NULL,
                    ""ExceptionsJSON"" text NULL,
                    ""ResultsJSON""    text NULL,
                    ""RunByUserName""  varchar(255) NULL,
                    ""LastEditedByUserName"" varchar(255) NULL,
                    ""LastEditedAt""   timestamptz NULL,
                    ""PreviousHash""   varchar(128) NULL,
                    ""RecordHash""     varchar(128) NULL,
                    ""IsCurrent""      boolean NOT NULL DEFAULT true,
                    ""WorkspaceSavedAt"" timestamptz NULL
                );",

                @"CREATE TABLE IF NOT EXISTS ""AuditLog"" (
                    ""LogID""        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserID""       text NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""Action""       varchar(255) NOT NULL,
                    ""EntityType""   varchar(100) NULL,
                    ""EntityID""     integer NULL,
                    ""OldValues""    text NULL,
                    ""NewValues""    text NULL,
                    ""IPAddress""    varchar(50) NULL,
                    ""Timestamp""    timestamptz NOT NULL DEFAULT now(),
                    ""PreviousHash"" varchar(128) NULL,
                    ""RecordHash""   varchar(128) NULL
                );",

                @"CREATE TABLE IF NOT EXISTS ""ReviewSignoffs"" (
                    ""SignoffID""   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ClientID""    integer NOT NULL REFERENCES ""Clients""(""ClientID""),
                    ""RunID""       integer NULL REFERENCES ""ValidationRuns""(""RunID""),
                    ""ReviewerID""  text NOT NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""SignoffRole"" varchar(50) NOT NULL DEFAULT 'DataAnalyst',
                    ""ReviewType""  varchar(50) NOT NULL CHECK (""ReviewType"" IN ('Preliminary','Final')),
                    ""Comment""     text NULL,
                    ""SignedOffAt"" timestamptz NOT NULL DEFAULT now(),
                    CONSTRAINT ""UQ_ReviewSignoffs_Run_Reviewer"" UNIQUE (""RunID"", ""ReviewerID"")
                );",

                @"CREATE TABLE IF NOT EXISTS ""PasswordResetTokens"" (
                    ""TokenID""   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserID""    text NOT NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""Token""     varchar(500) NOT NULL UNIQUE,
                    ""ExpiresAt"" timestamptz NOT NULL,
                    ""Used""      boolean NOT NULL DEFAULT false,
                    ""CreatedAt"" timestamptz NOT NULL DEFAULT now()
                );",

                @"CREATE TABLE IF NOT EXISTS ""ImpersonationLog"" (
                    ""ImpersonationID""    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""AdminUserID""        text NOT NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""ImpersonatedRole""   varchar(50) NOT NULL,
                    ""ImpersonatedUserID"" text NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""StartedAt""          timestamptz NOT NULL DEFAULT now(),
                    ""EndedAt""            timestamptz NULL
                );",

                @"CREATE TABLE IF NOT EXISTS ""MessageThreads"" (
                    ""ThreadID""        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ClientID""        integer NULL REFERENCES ""Clients""(""ClientID""),
                    ""Subject""         varchar(255) NOT NULL,
                    ""CreatedByUserID"" text NOT NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""CreatedAt""       timestamptz NOT NULL DEFAULT now(),
                    ""LastMessageAt""   timestamptz NOT NULL DEFAULT now(),
                    ""PreviousHash""    varchar(128) NULL,
                    ""RecordHash""      varchar(128) NULL
                );",

                @"CREATE TABLE IF NOT EXISTS ""ThreadMessages"" (
                    ""MessageID""        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ThreadID""         integer NOT NULL REFERENCES ""MessageThreads""(""ThreadID""),
                    ""SenderUserID""     text NOT NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""Body""             text NOT NULL,
                    ""ReplyToMessageID"" integer NULL REFERENCES ""ThreadMessages""(""MessageID""),
                    ""SentAt""           timestamptz NOT NULL DEFAULT now(),
                    ""PreviousHash""     varchar(128) NULL,
                    ""RecordHash""       varchar(128) NULL,
                    ""EditedAt""         timestamptz NULL,
                    ""IsDeleted""        boolean NOT NULL DEFAULT false,
                    ""DeletedAt""        timestamptz NULL
                );",

                @"CREATE TABLE IF NOT EXISTS ""ThreadMessageRecipients"" (
                    ""RecipientID"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""MessageID""   integer NOT NULL REFERENCES ""ThreadMessages""(""MessageID""),
                    ""UserID""      text NOT NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""IsRead""      boolean NOT NULL DEFAULT false,
                    ""ReadAt""      timestamptz NULL,
                    CONSTRAINT ""UQ_ThreadMessageRecipients_Message_User"" UNIQUE (""MessageID"", ""UserID"")
                );",

                @"CREATE TABLE IF NOT EXISTS ""ThreadUserStates"" (
                    ""StateID""   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ThreadID""  integer NOT NULL REFERENCES ""MessageThreads""(""ThreadID""),
                    ""UserID""    text NOT NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""IsDeleted"" boolean NOT NULL DEFAULT false,
                    ""DeletedAt"" timestamptz NULL,
                    CONSTRAINT ""UQ_ThreadUserStates_Thread_User"" UNIQUE (""ThreadID"", ""UserID"")
                );",

                @"CREATE TABLE IF NOT EXISTS ""ThreadMessageAttachments"" (
                    ""AttachmentID""   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""MessageID""      integer NOT NULL REFERENCES ""ThreadMessages""(""MessageID""),
                    ""FileName""       varchar(255) NOT NULL,
                    ""FilePath""       varchar(500) NOT NULL,
                    ""ContentType""    varchar(100) NOT NULL,
                    ""FileSize""       bigint NOT NULL,
                    ""AttachmentKind"" varchar(20) NOT NULL DEFAULT 'file',
                    ""CreatedAt""      timestamptz NOT NULL DEFAULT now()
                );",

                @"CREATE TABLE IF NOT EXISTS ""ClientFavorites"" (
                    ""FavoriteID"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserID""     text NOT NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""ClientID""   integer NOT NULL REFERENCES ""Clients""(""ClientID""),
                    ""CreatedAt""  timestamptz NOT NULL DEFAULT now(),
                    CONSTRAINT ""UQ_ClientFavorites_User_Client"" UNIQUE (""UserID"", ""ClientID"")
                );",

                @"CREATE TABLE IF NOT EXISTS ""EngagementRuleScope"" (
                    ""ScopeID""         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ClientID""        integer NOT NULL REFERENCES ""Clients""(""ClientID""),
                    ""RuleNumber""      integer NOT NULL,
                    ""AddedAt""         timestamptz NOT NULL DEFAULT now(),
                    ""AddedByUserID""   text NOT NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""AddedByUserName"" varchar(200) NOT NULL DEFAULT '',
                    CONSTRAINT ""UQ_EngagementRuleScope_Client_Rule"" UNIQUE (""ClientID"", ""RuleNumber"")
                );",

                // One named "database" per engagement — the data analyst creates this first;
                // it's a friendly label over the engagement's own Postgres schema
                // (engagement_{ClientID}, always computed server-side, never from this name).
                // Uploads are blocked until a row exists here for the engagement.
                @"CREATE TABLE IF NOT EXISTS ""EngagementDatabases"" (
                    ""ClientID""        integer PRIMARY KEY REFERENCES ""Clients""(""ClientID""),
                    ""DatabaseName""    varchar(200) NOT NULL,
                    ""SchemaName""      varchar(100) NOT NULL DEFAULT '',
                    ""CreatedByUserID"" text NOT NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""CreatedAt""       timestamptz NOT NULL DEFAULT now()
                );",

                // CREATE TABLE IF NOT EXISTS above won't retroactively add this column to a
                // table created before SchemaName existed, so make sure it's really there.
                @"ALTER TABLE ""EngagementDatabases"" ADD COLUMN IF NOT EXISTS ""SchemaName"" varchar(100) NOT NULL DEFAULT '';",

                // Tracks a dataset upload's progress once it's handed off to the background
                // import worker, so a huge file (millions of rows) can be imported without
                // tying up the HTTP request that started it — the browser polls this row's
                // Status/ProcessedRows instead of waiting on the request to complete.
                @"CREATE TABLE IF NOT EXISTS ""DatasetUploadJobs"" (
                    ""JobID""           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ClientID""        integer NOT NULL REFERENCES ""Clients""(""ClientID""),
                    ""TableName""       varchar(100) NOT NULL,
                    ""Token""           varchar(64) NOT NULL,
                    ""Status""          varchar(20) NOT NULL DEFAULT 'Queued'
                                        CHECK (""Status"" IN ('Queued','Running','Completed','Failed')),
                    ""TotalRows""       bigint NULL,
                    ""ProcessedRows""   bigint NOT NULL DEFAULT 0,
                    ""ErrorMessage""    text NULL,
                    ""CreatedByUserID"" text NOT NULL REFERENCES ""AspNetUsers""(""Id""),
                    ""CreatedAt""       timestamptz NOT NULL DEFAULT now(),
                    ""StartedAt""       timestamptz NULL,
                    ""CompletedAt""     timestamptz NULL
                );",
                @"CREATE INDEX IF NOT EXISTS ""IX_DatasetUploadJobs_Client"" ON ""DatasetUploadJobs"" (""ClientID"");"
            };

            foreach (var ddl in ddlStatements)
            {
                await using var command = connection.CreateCommand();
                command.CommandText = ddl;
                await command.ExecuteNonQueryAsync();
            }

            var indexStatements = new[]
            {
                @"CREATE INDEX IF NOT EXISTS ""IX_Clients_FirmID"" ON ""Clients"" (""FirmID"");",
                @"CREATE INDEX IF NOT EXISTS ""IX_ValidationRuns_Client_Rule_Current"" ON ""ValidationRuns"" (""ClientID"", ""RuleNumber"", ""IsCurrent"");",
                @"CREATE INDEX IF NOT EXISTS ""IX_AuditLog_Timestamp"" ON ""AuditLog"" (""Timestamp"");",
                @"CREATE INDEX IF NOT EXISTS ""IX_AuditLog_UserID"" ON ""AuditLog"" (""UserID"");",
                @"CREATE INDEX IF NOT EXISTS ""IX_MessageThreads_Client_LastMessage"" ON ""MessageThreads"" (""ClientID"", ""LastMessageAt"");",
                @"CREATE INDEX IF NOT EXISTS ""IX_ThreadMessages_Thread_SentAt"" ON ""ThreadMessages"" (""ThreadID"", ""SentAt"");",
                @"CREATE INDEX IF NOT EXISTS ""IX_ThreadMessageRecipients_User_Read"" ON ""ThreadMessageRecipients"" (""UserID"", ""IsRead"");",
                @"CREATE INDEX IF NOT EXISTS ""IX_ThreadUserStates_User_Deleted"" ON ""ThreadUserStates"" (""UserID"", ""IsDeleted"");",
                @"CREATE INDEX IF NOT EXISTS ""IX_ThreadMessageAttachments_Message"" ON ""ThreadMessageAttachments"" (""MessageID"");",
                @"CREATE INDEX IF NOT EXISTS ""IX_ClientFavorites_User"" ON ""ClientFavorites"" (""UserID"");"
            };

            foreach (var ddl in indexStatements)
            {
                await using var command = connection.CreateCommand();
                command.CommandText = ddl;
                await command.ExecuteNonQueryAsync();
            }
        }
    }
}
